### ISSUE TITLE
kv_store seems to limit "clusters" module to one core

### ISSUE THREAD

**Issue by haakonnessjoen** [SyntheticSemantics/ems#13]
Hi,

I did some testing using Examples\kv_store.js as a starting point. And even if I was not using any of the ems function (other than initializing it), the cluster module suddenly was not able to do more than one core's worth of cpu, even though I could see it had several slave processes running.

It do seem to be related to the "threadAffinity" option of ems. When I set this to false in the initialization, it seems that 'cluster' recovers its powers.

Isn't it weird to make an example use the node js cluster module, but limit its strength back to where you would be without it. (or in fact worse)

**Comment by mogill** [comment]
Hi Håkon,

If by "weird" you mean "buggy", then yes, this example incorrectly pins all the user cluster processes to core 0.
The default is to not pin processes to cores, and all the other tests and examples correctly set this argument.

Thank you for spotting this performance regression!  I owe you a refreshing beverage.  This bug is fixed in v1.4.2, just pushed.  Please let me know if you spot other performance errors!

**Comment by haakonnessjoen** [comment]
Great :) Then I guess it is solved!
